export default {
  inbox: [
    {
      title: "Twitch Stream",
      subject: "Hello Emiz",
      description: "This is the description",
      time: "11.54 P.M.",
      important: false,
    },
    {
      title: "Twitch Stream",
      subject: "Hello Emiz",
      description: "This is the description",
      time: "11.54 P.M.",
      important: false,
    },
    {
      title: "Twitch Stream",
      subject: "Hello Emiz",
      description: "This is the description",
      time: "11.54 P.M.",
      important: true,
    },
    {
      title: "Twitch Stream",
      subject: "Hello Emiz",
      description: "This is the description",
      time: "11.54 P.M.",
      important: true,
    },
    {
      title: "Twitch Stream",
      subject: "Hello Emiz",
      description: "This is the description",
      time: "11.54 P.M.",
      important: false,
    },
    {
      title: "Twitch Stream",
      subject: "Hello Emiz",
      description: "This is the description",
      time: "11.54 P.M.",
      important: false,
    },
    {
      title: "Twitch Stream",
      subject: "Hello Emiz",
      description: "This is the description",
      time: "11.54 P.M.",
      important: true,
    },
    {
      title: "Twitch Stream",
      subject: "Hello Emiz",
      description: "This is the description",
      time: "11.54 P.M.",
      important: false,
    },
    {
      title: "Twitch Stream",
      subject: "Hello Emiz",
      description: "This is the description",
      time: "11.54 P.M.",
      important: false,
    },
    {
      title: "Twitch Stream",
      subject: "Hello Emiz",
      description: "This is the description",
      time: "11.54 P.M.",
      important: false,
    },
    {
      title: "Twitch Stream",
      subject: "Hello Emiz",
      description: "This is the description",
      time: "11.54 P.M.",
      important: true,
    },
    {
      title: "Twitch Stream",
      subject: "Hello Emiz",
      description: "This is the description",
      time: "11.54 P.M.",
      important: false,
    },
    {
      title: "Twitch Stream",
      subject: "Hello Emiz",
      description: "This is the description",
      time: "11.54 P.M.",
      important: false,
    },
    {
      title: "Twitch Stream",
      subject: "Hello Emiz",
      description: "This is the description",
      time: "11.54 P.M.",
      important: true,
    },
    {
      title: "Twitch Stream",
      subject: "Hello Emiz",
      description: "This is the description",
      time: "11.54 P.M.",
      important: true,
    },
    {
      title: "Twitch Stream",
      subject: "Hello Emiz",
      description: "This is the description",
      time: "11.54 P.M.",
      important: true,
    },
    {
      title: "Twitch Stream",
      subject: "Hello Emiz",
      description: "This is the description",
      time: "11.54 P.M.",
      important: false,
    },
    {
      title: "Twitch Stream",
      subject: "Hello Emiz",
      description: "This is the description",
      time: "11.54 P.M.",
      important: false,
    },
    {
      title: "Twitch Stream",
      subject: "Hello Emiz",
      description: "This is the description",
      time: "11.54 P.M.",
      important: false,
    },
    {
      title: "Twitch Stream",
      subject: "Hello Emiz",
      description: "This is the description",
      time: "11.54 P.M.",
      important: false,
    },
    {
      title: "Twitch Stream",
      subject: "Hello Emiz",
      description: "This is the description",
      time: "11.54 P.M.",
      important: false,
    },
    {
      title: "Twitch Stream",
      subject: "Hello Emiz",
      description: "This is the description",
      time: "11.54 P.M.",
      important: false,
    },
    {
      title: "Twitch Stream",
      subject: "Hello Emiz",
      description: "This is the description",
      time: "11.54 P.M.",
      important: true,
    },
    {
      title: "Twitch Stream",
      subject: "Hello Emiz",
      description: "This is the description",
      time: "11.54 P.M.",
      important: false,
    },
    {
      title: "Twitch Stream",
      subject: "Hello Emiz",
      description: "This is the description",
      time: "11.54 P.M.",
      important: true,
    },
    {
      title: "Twitch Stream",
      subject: "Hello Emiz",
      description: "This is the description",
      time: "11.54 P.M.",
      important: true,
    },
  ],
};
